version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: company-crud_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: company_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company-crud_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/company_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    ports:
      - "8082:8080"

volumes:
  postgres_data:
